# This is a config for E2B sandbox template.
# You can use template ID (rsstedzotjqmvtvqkb9z) or template name (desktop-groq) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("desktop-groq") # Sync sandbox
# sandbox = await AsyncSandbox.create("desktop-groq") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('desktop-groq')

template_id = "rsstedzotjqmvtvqkb9z"
dockerfile = "e2b.Dockerfile"
template_name = "desktop-groq"
start_cmd = "/start_command.sh"
cpu_count = 8
memory_mb = 8_192
team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
